import path from "path"
import tailwindcss from "@tailwindcss/vite"
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'
import { tanstackRouter } from '@tanstack/router-plugin/vite'


export default defineConfig({
  plugins: [
    tanstackRouter({
      target: 'react',
      autoCodeSplitting: true,
      routesDirectory: path.resolve(__dirname, './src/pages'),
      generatedRouteTree: path.resolve(__dirname, './src/pages/routeTree.gen.ts'),
      routeTreeFileHeader: [
        '/* eslint-disable */',
        '',
        '// @ts-nocheck',
        '',
        '// noinspection JSUnusedGlobalSymbols',
        '',
        '// This file was automatically generated by TanStack Router.',
        '// You should NOT make any changes in this file as it will be overwritten.',
        '// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.',
      ],
      routeFilePrefix: '',
    }),
    react(),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
})